# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: ssl-d_first_step
# label used for menu selection
label: ssl-d_first_step
description: Basic Forward Proxy rule for URL categories that may not be blocked, have a higher chance of containing malware and a low chance of containing compliance related data.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - ssl-d

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: trust
    description: Internal zone name
    default: trust
    type_hint: text
  - name: untrust
    description: Internet zone name
    default: untrust
    type_hint: text

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: decrypt-rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/decryption/rules
    file: decrypt-rules.xml
# ---------------------------------------------------------------------
# end of snippets section